{{- range .Values.roleBindings }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .group | quote }}
  namespace: {{ $.Release.Namespace | quote }}
subjects:
- kind: "Group"
  name: {{ .group | quote }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: {{ .roleKind | default "ClusterRole" | quote }}
  name: {{ .role | quote }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}