apiVersion: v1
kind: Service
metadata:
  name: istiocoredns
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istiocoredns.name" . }}
    chart: {{ template "istiocoredns.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: istiocoredns
{{- if .Values.clusterIP }}
    clusterIP: "{{ .Values.clusterIP }}"
{{- end }}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
